---
# tasks file for sf.main_config
- name: Configure SolidFire using JSON Body Files
  uri:
    url: "{{ sf_api_url }}"
    method: POST
    user: "{{ sf_username }}"
    password: "{{ sf_password }}"
    force_basic_auth: yes
    body_format: json
    validate_certs: false
    body: "{{ item }}"
  with_file:
    - ntp.json
    - adminUsers.json

