---
# tasks file for sf.create_cluster
- name: Create Cluster
  uri:
    url: "{{ sf_api_url }}"
    method: POST
    user: "{{ sf_username }}"
    password: "{{ sf_password }}"
    body:
      method: CreateCluster
      params:
        acceptEula: true
        mvip: "{{ sf_cluster_mvip }}"
        svip: "{{ sf_cluster_svip }}"
        repCount: "{{ sf_repCount }}"
        username: "{{ sf_username }}"
        password: "{{ sf_password }}"
        attributes:
          clusteraccountnumber: "{{ sf_cluster_account_number }}"
        nodes:
        - "{{ sf_node1_ip }}"
        - "{{ sf_node2_ip }}"
        - "{{ sf_node3_ip }}"
        - "{{ sf_node4_ip }}"
      id: 1
    force_basic_auth: yes
    body_format: json
    validate_certs: false
