---
# tasks file for sf.concheck
- name: 
  sf_check_connections:
    hostname: "{{ sf_hostname }}"
    username: "{{ sf_username }}"
    password: "{{ sf_password }}"

- name: Add user
  sf_account_manager:
    hostname: "{{ sf_hostname }}"
    username: "{{ sf_username }}"
    password: "{{ sf_password }}"
    state: present
    name: lee
      
- name: List User Accounts
  uri:
    url: "{{ sf_api_url }}"
    method: POST
    user: "{{ sf_username }}"
    password: "{{ sf_password }}"
    body: 
      method: ListAccounts
      params:
        startAccountID: 0
        limit: 1000
      id: 1
    force_basic_auth: yes
    body_format: json
    validate_certs: false
